### PR TITLE
Updated notifier/notifier.scpt to use /usr/bin/tail, in case users have coreutils installed and GNU tail in their PATH

### LINKED ISSUE #37: "Logs not found; cannot show summary!"
Getting this error in the macOS notification when rebooting and autoupdate is running.

Anything I can do to fix this? Or some trace/logs I can look at to look into it?

### PR DESCRIPTION
**Pull request by ndbroadbent**
Fixes #37 

GNU tail doesn't support the `-r` flag, so that's why it was failing for me and running the "on error" section:

```
try
	set tailLog to do shell script "tail -r ~/Library/Logs/com.github.domt4.homebrew-autoupdate/*.out | grep -E -m1 'taps|date'"
on error
	set tailLog to "Logs not found; cannot show summary!"
end try
```

Can be fixed by using `/usr/bin/tail -r`, which is the default tail that comes with macOS.

### Before:

Screen Shot 2022-10-08 at 1 22 48 PM

### After:

```
cp notifier/notifier.scpt /usr/local/Homebrew/Library/Taps/homebrew/homebrew-autoupdate/notifier/brew-autoupdate.app/Contents/Resources/Scripts/main.scpt
launchctl start com.github.domt4.homebrew-autoupdate
```

Screen Shot 2022-10-08 at 1 25 48 PM

### CODE REVIEW

**Comment by ndbroadbent** [comment]
I also just noticed there's a bug with the log parsing. `grep -E -m1 'taps|date'"` is matching the `or list them with brew outdated.` line in the logs:

```
assimp
aom
ansible
adwaita-icon-theme
==> Outdated Formulae
Updated 1 tap (homebrew/cask).
Sat Oct  8 13:25:11 NZDT 2022
or list them with brew outdated.
You can upgrade them with brew upgrade
You have 178 outdated formulae and 13 outdated casks installed.

virtualbox
rescuetime
qbittorrent
postico
playonmac
...
```

**Comment by troyfisher** [comment]
Also confirming this fixes the specific scenario of GNU coreutils installed (tested locally), great work @ndbroadbent. Can the PR be expedited?

**Comment by troyfisher** [comment]
Alternatively, if this is not a desirable change perhaps using `tac` rather than `tail -r` could be considered. The same reversed output of the log is created by tac natively whether using native MacOS binaries or GNU Coreutils.

**Comment by ndbroadbent** [comment]
@troyfisher Thanks for the tip about `tac`, I didn't know about that! I will update to use that

**Pull request closed without merging**
