### PR TITLE
(Reopen #92) Updated notifier/notifier.scpt to use /usr/bin/tail

### PR DESCRIPTION
**Pull request by sargunv**
The issue still persists but the previous PR was closed as stale, so I'm reopening it.

https://github.com/Homebrew/homebrew-autoupdate/pull/92

### CODE REVIEW

**Comment by DomT4** [comment]
Hi @sargunv. Thanks for the PR! Apologies if you've submitted one before with the bot closing it; truth be told I've got a lot of things I'd like to do with this project but find it very hard to find the time working the hours I do IRL.

Does the `tail` from coreutils behave differently from the macOS equivalent in certain circumstances as used by the applet? Just curious more than anything else.

**Comment by DomT4** [comment]
Just glanced through the originally linked PR. Will let the test bot check this over but looks a sensible couple of changes.

**Comment by sargunv** [comment]
> Apologies if you've submitted one before with the bot closing it

No worries! Just wanted to keep one open so it didn't get missed later. The first PR actually wasn't mine, I just reopened it with the original person's branch.

**Comment by DomT4** [comment]
Merged. Thanks for picking this back up @sargunv, and thanks to @ndbroadbent for the original PR & changes.

I will have to recompile the applet at some point for this to take effect; I need to reactivate my Apple developer ID first so I can codesign the applet, as I didn't want to pay the £79 or whatever it is at the moment when my full-time job essentially prevents me from doing any development work these days.

**Comment by sargunv** [comment]
Oh, Apple 🙃 

I'd be happy to pitch in some part of that fee if there's an easy way to get the money to you.

**Pull request closed without merging**
